#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    vehicle = bld.path.name
    with open("AntennaTracker/directories_list") as f:
        bld.ap_stlib(
            name=vehicle + '_libs',
            ap_vehicle=vehicle,
            ap_libraries=bld.ap_common_vehicle_libraries() + [l.rstrip() for l in f],
        )

    bld.ap_program(
        program_name='antennatracker',
        program_groups=['bin', 'antennatracker'],
        use=vehicle + '_libs',
    )
